### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by JustinDevB** [scomans/MyPet#1464]
# Bug report
* [* ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Console is being spammed whenever people ride a pet.
https://pastebin.com/6upCjs7A

## To Reproduce

Ride a pet
...

## Expected behavior

Console to not be spammed

## Actual behaviour

Console is spammed

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
[ticket.zip](https://github.com/scomans/MyPet/files/6488413/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**
Purpur: This server is running Purpur version git-Purpur-1078 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 33 version(s) behind
Previous version: git-Purpur-1060 (MC: 1.16.5)
**MyPet Build/Version:**
3.11
**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by destro174** [comment]
Update purpur to atleast build 1091 to fix this.
