### ISSUE TITLE
Is it possible to create custom pets (like hovering items or alike) by hooking into the plugin somehow?

### ISSUE THREAD

**Issue by Lubjan** [scomans/MyPet#1465]
For an upcoming server, we want to enable our users to have pets - not limiting them to base mobs - but also something like a dropped item with particles around it or in general "particle clouds".

I've seen #895 but I'm not asking you to add this as a feature, rather to clarify if it is possible for someone else to add new pets from the outside, as I did not find any information on that topic in the wiki (excuse me if I overlooked it).

* [ ] I have asked for help on other places like Discord or the discussion on spigotmc.org

**Comment by scomans** [comment]
No that's not possible.

**Comment by Lubjan** [comment]
Thank you for the quick answer, have a great day.
