### ISSUE TITLE
MyPet will be updated to 1.17 version ?

### ISSUE THREAD

**Issue by comonier** [scomans/MyPet#1478]
want to know to decide if i will remove mypet from plugins list of the server announce.

**Comment by ScuroK** [comment]
same here. some more infos would be appreciated so that i know whats the case. i tried to find out more on dc but it seems like the dev is a bit tired of supporting so many users there. im wondering if mypet got discontinued. im using it for soooo many years. would be sad

**Comment by andris155** [comment]
There is an updated version to 1.17, but for me maven compilation unfortunately doesn't work.
https://github.com/mofucraft/MyPet

**Comment by scomans** [comment]
@nafu-at are your changes ready to be merged into this repo? Is there anything not working yet?

**Comment by nafu-at** [comment]
> @nafu-at are your changes ready to be merged into this repo? Is there anything not working yet?

I don't have much experience in developing plugins that work directly with Minecraft Server, and I lack the knowledge needed to complete it.
Therefore, more time is needed to complete the work.
Also, there is no support for the mobs added in v1.17.

I'm willing to help the repository achieve this goal.
If there is anything I should do, please let me know.

**Comment by destro174** [comment]
> > @nafu-at are your changes ready to be merged into this repo? Is there anything not working yet?
> 
> Unfortunately, the fork I created does not work yet.
> I don't have much experience in developing plugins that work directly with Minecraft Server, and I lack the knowledge needed to complete it.
> Therefore, more time is needed to complete the work.
> Also, there is no support for the mobs added in v1.17.
> 
> I'm willing to help the repository achieve this goal.
> If there is anything I should do, please let me know.

I checked out your fork, it's looking good, what's the issues with it? should compile once you setup java toolchain

**Comment by nafu-at** [comment]
> I checked out your fork, it's looking good, what's the issues with it? should compile once you setup java toolchain

I think the code fix is going well.
However, I haven't been able to check the actual behavior because the build didn't succeed.
When I try to build it in Java 16, I get an " cannot access" error.

**Comment by andris155** [comment]
> > I checked out your fork, it's looking good, what's the issues with it? should compile once you setup java toolchain
> 
> I think the code fix is going well.
> However, I haven't been able to check the actual behavior because the build didn't succeed.
> When I try to build it in Java 16, I get an " cannot access" error.

Try build it in Java 11.

**Comment by destro174** [comment]
> > I checked out your fork, it's looking good, what's the issues with it? should compile once you setup java toolchain
> 
> I think the code fix is going well.
> However, I haven't been able to check the actual behavior because the build didn't succeed.
> When I try to build it in Java 16, I get an " cannot access" error.

compile all modules but the 1.17 module in jdk8, then use toolchain to compile module 1.17 in jdk16

You can't compile it in jdk11 as 1.17 requires 16

**Comment by devbaraus** [comment]
Any news?

**Comment by ScuroK** [comment]
Any news @TitanDevX @scomans 
???

**Comment by CJBlakey** [comment]
I see that @nafu-at as recently made some commits to their repo. Were you able to get it to compile?

**Comment by ScuroK** [comment]
Someone called „Destro“ wrote on the mypet-dc that he was able to update it. But it seems like he wont share his updated cersion for now :/

**Comment by CJBlakey** [comment]
> Someone called „Destro“ wrote on the mypet-dc that he was able to update it. But it seems like he wont share his updated version for now :/

How in keeping with the community values of an open source plugin :/

**Comment by SirCraftypants** [comment]
> 
> 
> > Someone called „Destro“ wrote on the mypet-dc that he was able to update it. But it seems like he wont share his updated version for now :/
> 
> How in keeping with the community values of an open source plugin :/

does community values even exist? After all the only questions i ever asked on Mypets Discord were as follows.

When is it being updated to 1.16 (this was just after 1.16 release) and i got my answer, directed to the dev build.

Then i asked for Bees to be added but didn't get a reply and months later after trying to return to Mypet discord.

I find out i'm banned and can not access Mypet discord. I think these supposed values are lacking if people are being banned for just asking questions. I ended up removing Mypet on release of 1.16 but i've kept my eye on this guthub out of sheer interest in having a fork made. Cos i hate using plugins without discord access or good github support.

**Comment by SirCraftypants** [comment]
> 
> 
> > Someone called „Destro“ wrote on the mypet-dc that he was able to update it. But it seems like he wont share his updated version for now :/
> 
> How in keeping with the community values of an open source plugin :/

Or maybe they're just blagging it for some reason (wind up maybe) and haven't really updated it at all, answering why they won't share it.

**Comment by CJBlakey** [comment]
> > > Someone called „Destro“ wrote on the mypet-dc that he was able to update it. But it seems like he wont share his updated version for now :/
> > 
> > 
> > How in keeping with the community values of an open source plugin :/
> 
> does community values even exist? After all the only questions i ever asked on Mypets Discord were as follows.
> 
> When is it being updated to 1.16 (this was just after 1.16 release) and i got my answer, directed to the dev build.
> 
> Then i asked for Bees to be added but didn't get a reply and months later after trying to return to Mypet discord.
> 
> I find out i'm banned and can not access Mypet discord. I think these supposed values are lacking if people are being banned for just asking questions. I ended up removing Mypet on release of 1.16.3 but i've kept my eye on this guthub out of sheer interest in having a fork made. Cos i hate using plugins without discord access or good github support.

The devs announced long ago that they didn’t intend on regularly adding features to mypets, we as a community are lucky to receive any updates at all, so the devs are well within their rights to ban people who don’t seem to understand that.

This plugin is great, but it’s also a whole lot of work and the only 2 core devs have lives of their own, you’re welcome to submit your own code but don’t get upset when 2 adults with their own lives don’t do it for free

**Comment by SirCraftypants** [comment]
how is asking a simple innocent question a ban offence, seriously? So have every single person who dared to ask for a mod to be added been banned. Sounds a little Russian or Chinese to me.

**Comment by CJBlakey** [comment]
> how is asking a simple innocent question a ban offence, seriously? So have every single person who dared to ask for a mob to be added been banned. Sounds a little Russian or Chinese Communism to me.

I’m not suggesting it is, but you’ve posted the same comments here, and on their spigot mc page discussions and their discord. I get the ban.

**Comment by ScuroK** [comment]
i think many people are just frustrated about the lack of communication. i can understand that :/ and i think frustration can make ppl say things in ruff way. 

just to be clear, here is what he wrote: "I have An updated mypet fork and will pr it back upstream once the server i work for has fully updated".
i assume that a server has paid him to update it only for them. im just guessing.

@destro174 is that you?

**Comment by SirCraftypants** [comment]
> 
> 
> > how is asking a simple innocent question a ban offence, seriously? So have every single person who dared to ask for a mob to be added been banned. Sounds a little Russian or Chinese Communism to me.
> 
> I’m not suggesting it is, but you’ve posted the same comments here, and on their spigot mc page discussions and their discord. I get the ban.

That's a flat outright lie. I've never said anything bad on mypets discord ever and challenge you to prove otherwise, Yes i left a poor review and i had every right too after being banned for asking a simple innocent question, all they had to do was say no or ignore me, but ban me? do you seriously think banning someone for an innocent question is justifiable? I provide support for a Premium Plugin myself, if i went banning everyone for asking a simple innocent, then how do you think that would affect the developer and their product? Yeah Mypets open source but, does that mean standards should drop and people should be treated with disdain.

**Comment by SirCraftypants** [comment]
> 
> 
> i think many people are just frustrated about the lack of communication. i can understand that :/ and i think frustration can make ppl say things in ruff way.
> 
> just to be clear, here is what he wrote: "I have An updated mypet fork and will pr it back upstream once the server i work for has fully updated".
> i assume that a server has paid him to update it only for them. im just guessing.
> 
> @destro174 is that you?

No it's not me.

**Comment by ScuroK** [comment]
i guess the devs are just overwhelmed. maybe thats why they ban people sometimes.
a clear statement from TitanDev might help.

**Comment by ScuroK** [comment]
if anyone is interested, here is Destros answer: https://discord.com/channels/145501914795212800/439337867005919232/873613072835687339

**Comment by furkanaliunal** [comment]
I think mob behaviours are a serious problem

**Comment by nafu-at** [comment]
> I see that @nafu-at as recently made some commits to their repo. Were you able to get it to compile? 

The fork I tried to create was also just a conversion of 1.16.5 to work with 1.17.
However, I've been having problems with the build not completing properly, and I've asked several people I know for advice on how to solve the problem, but I haven't been able to solve it, so development is not moving forward.
If you have any good ideas, please report them to me.
I will be happy to share my code as soon as I know that it works correctly.

Translated with www.DeepL.com/Translator (free version)

**Comment by CJBlakey** [comment]
@destro174 & @nafu-at & @andris155, I can see that between your repos you seem to have done a bunch of updating, is there anything outstanding that we as a community can help with?

as I see it, a conversion of 1.16.5 to 1.17.1 would be better than nothing, is there a task list of outstanding work left to achieve that? if not would it be helpful for us to raise a separate issue where we can create a list of the completed/outstanding work required to achieve either a minimum viable 1.17.1 version of the plugin (a 1.16.5 conversion) or if possible between the community a fully fledged update to include new mobs and fix erroneous behaviours?

**Comment by Jakllp** [comment]
Hi
I recently forked mofucat's fork and did some more work to get it to 1.17.1 (and 1.17 but I only have that locally right now)
Long story short:
It's compilable and the server starts without throwing errors.

(and I got rid of that annoying 401 Error bc of github packages. Well I found it to be annoying at least.)

**Comment by andris155** [comment]
> Hi
> I recently forked mofucat's fork and did some more work to get it to 1.17.1 (and 1.17 but I only have that locally right now)
> Long story short:
> It's compilable and the server starts without throwing errors.
> 
> I don't however know how to actually use the plugin so... I can't really test it. So yeah.
> If anyone could test this and potentially provide feedback then that would be great.
> You can find a jar [here](https://github.com/Jakllp/MyPet/releases/tag/v1.17.1-dev1).
> 
> The new 1.17 mobs aren't integrated yet (I added them in MyAttributeDefaults.java but didn't add MyEntity* classes).
> Contributions to the repo are always appreciated!
> 
> (and I got rid of that annoying 401 Error bc of github packages. Well I found it to be annoying at least.)

The server starts without error, but not work without errors.
/pc:
<img width="340" alt="Screenshot 2021-08-17 232119" src="https://user-images.githubusercontent.com/8324198/129802320-0a68db1c-a413-4604-8a06-5bcf7e79e5a8.png">


```
[23:18:14 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMyCow(Cow) is no valid MyPet(Entity)!
[23:18:14 WARN]: java.lang.reflect.InvocationTargetException
[23:18:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:18:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[23:18:14 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:18:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[23:18:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityRegistry.createMinecraftEntity(EntityRegistry.java:92)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:473)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:481)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62)
[23:18:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:18:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[23:18:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[23:18:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[23:18:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[23:18:14 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeProvider.a(java.util.function.Consumer, net.minecraft.world.entity.ai.attributes.AttributeBase)" because "this.d" is null
[23:18:14 WARN]:        at net.minecraft.world.entity.ai.attributes.AttributeMapBase.lambda$getInstance$1(AttributeMapBase.java:50)
[23:18:14 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[23:18:14 WARN]:        at net.minecraft.world.entity.ai.attributes.AttributeMapBase.a(AttributeMapBase.java:49)
[23:18:14 WARN]:        at net.minecraft.world.entity.EntityLiving.getAttributeInstance(EntityLiving.java:2407)
[23:18:14 WARN]:        at net.minecraft.world.entity.EntityLiving.<init>(EntityLiving.java:293)
[23:18:14 WARN]:        at net.minecraft.world.entity.EntityInsentient.<init>(EntityInsentient.java:131)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.EntityMyPet.<init>(EntityMyPet.java:149)
[23:18:14 WARN]:        at MyPet-3.12-SNAPSHOT.jar//de.Keyle.MyPet.compat.v1_17_R1.entity.types.EntityMyCow.<init>(EntityMyCow.java:44)
[23:18:14 WARN]:        ... 17 more
```

**Comment by Jakllp** [comment]
Oh yeah didn't mention it in here: It WILL throw basically every error it has on you

**Comment by edyangel** [comment]
Impressive the simple fact that the plugin already works quite a bit.

these are some of the bugs i found,
/ pc does not work,

pet store items are invisible
[error MyPet.txt](https://github.com/scomans/MyPet/files/7011098/error.MyPet.txt)

**Comment by Jakllp** [comment]
Hey thanks for the input.

Some of these errors are already fixed, others I know of and then there are some I just scimmes over rn.

The fixes can be "experienced" in this jar https://github.com/Jakllp/MyPet/releases/tag/v1.17.1-dev2

If you want (and have the time) you can check all the errors again and then post issues on my fork (https://github.com/Jakllp/MyPet/issues).
If you don't have the time or smth that's fine, I'll look through it again later when I'm not as tired as rn. 

Again: Thanks for trying it and reporting back

**Comment by edyangel** [comment]
This version fixed quite a few problems  :D

I'll skip obvious problems

I made a list of mobs that have console bugs and mobs that die without being tamed.

I have configured the yml files a bit and I have not found any errors at the moment

[Error MyPet Mobs.txt](https://github.com/scomans/MyPet/files/7012449/Error.MyPet.Mobs.txt)

**Comment by Jakllp** [comment]
There is a official MyPet-Discord: https://discord.gg/GtcdWFw

**Comment by Catches** [comment]
@Jakllp I am extremely grateful and appreciative that you have took your own time and decided to make a fork to support 1.17.1 and later versions, and I know I can speak for so many others here that they are very thankful as well. And I hope the thanks will be returned to contributions, pull requests, and donations to your fork.

**Comment by CJBlakey** [comment]
@Jakllp totally agree with Catches! you're the man! I'm pretty new myself to java but I'm keeping an eye on your fork for any issues I can possibly lend a helping hand with.

**Comment by Jakllp** [comment]
Thanks for the kind words @CJBlakey and @Catches
There are already people contributing (by testing/reporting bugs) and there were/are already pull requests which is super nice (huge thanks to everyone! OpenSource is a pleasant experience ^^)

**Comment by scomans** [comment]
I also want to thank you (@Jakllp any everyone else who contributed) for your effort to update MyPet. It's nice to see that there are people who care about your work. Also nice to see that you get the pleasent OS experience I mostly haven't gotten in my nearly 10 years of MyPet development. Sometimes you have to let go for things to evolve 😉 

@Jakllp Do you plan to further update MyPet in the future or is this update a one time thing? If you plan to do more work in the future would it be a help when I transfer this repo to the https://github.com/orgs/MyPetORG organization and add you and everyone who wants to contribute to this org?

**Comment by Jakllp** [comment]
@scomans I don't really know yet.
As a few people suggested I'm currently working on Mojang-Mappings so that updating will become easier so... maybe?

But one thing about the MyPetORG: How can we add the new Mob-Names to the translation-files?
I found how to add translations for already existing entries but not how to add a new entry
(Need to add Name.Axolotl for example)

**Comment by scomans** [comment]
In the past all translations were managed by my own website for MyPet: https://translation.mypet-plugin.de/
As an Admin you could add phrases that users of that site can translate into their native language. Once a day these translations got pushed to the translation repo (https://github.com/MyPetORG/MyPet-Translations) and therefore would end up in the next build that got compiled. 
When I moved most of the ecosystem for MyPet to GitHub actions and into docker containers on my server I broke that translation system so it is not fully functional at the moment. I could fix that without a problem but I'm not sure if that is the best way for you and any other contibutor to still use that site/system. The whole MyPet ecosystem has a lot of moving parts because I wanted to have as much automated as I could.

**Comment by Jakllp** [comment]
Well the automation does sound nice.
The question is what is easier - handling pull requests to the repo or getting the automation back up and running

Btw: I just saw that LOLCAT is a supported language AND that one piece of lolcat snuck it's way into the german translation. I think that's funny

**Comment by scomans** [comment]
I think the problems with the site are just minor so it should be up and running quickly.

- The problem with PRs is that most common users have no clue how to use Git(Hub) properly. That's why I created the site in the first place.
- The problem with the site is that it was never intended to have users that add phrases beside me or have multiple admins (even tho it should be no problem to have more than one)

I will see what I can do.

What translation is it? As I did English/German/Lolcat/Upside Down I might just pasted the translation into the wrong language 😅

**Comment by Jakllp** [comment]
It's Message.Shop.SuccessStorage 

And sure for stuff like this that would be easier. I'm active on the official Discord so you can find me there (or I can add you if you tell me your tag/who you are on Discord)

**Comment by edyangel** [comment]
hi! @Jakllp i have a error, When attacking a pet, I disconnect from the server and the following appears on the console:



[Nuevo Documento de texto (2).txt](https://github.com/scomans/MyPet/files/7100669/Nuevo.Documento.de.texto.2.txt)

P.S: Thanks for your great work on this plugin 😄

**Comment by Jakllp** [comment]
@edyangel was this on RC2 or RC1?

**Comment by edyangel** [comment]
I don't understand what you mean, sorry, but the plugin version was MyPet-1.17.1-dev10

Can I have problems with the plugin oldmechanics?


mobs also disappear when they fight with my pet

**Comment by Jakllp** [comment]
Ahh the dev10-bugs ^^
It should be gone when you update to MyPet-3.12-RC2 (see my fork -> releases)

**Comment by Jakllp** [comment]
#1486 Just gonna leave this here (see the download-page)
