### ISSUE TITLE
[bug]pet respawn no cooldown, no penalty, have error message

### ISSUE THREAD

**Issue by hkkongou** [scomans/MyPet#1481]
# Bug report

* [✅] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

i found out that pet does not have any delay when pet die, they respawn immediately, and the owner does not take fines when the pet respawn immediately.

i have checked and tried to use, ``disabled: true`` or false, with different number of factor/fixed , still, does not work, i have got mypet setting running for more than 1 year, back in the day they have pet die delay, but i don't know when did the delay started not working.
```
  Respawn:
    Time:
      Disabled: false
      Default:
        Factor: 5
        Fixed: 0
      Player:
        Factor: 5
        Fixed: 0
    EconomyCost:
      Fixed: 0.0
      Factor: 1.0
```
## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. wipe mypet file, regen new mypet files
2. get in server, buy a pet
3. set pet high lv/ or not, 
4. kill the pet by any source, such as lava
5. error will show in console, pet instantly respawn, no fines for players
...

## Expected behavior

_A clear and concise description of what you expected to happen._

there should be some time need to wait for pet to spawn if it die

## Actual behaviour

pet spawn immediately, with error message

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

[ticket.zip](https://github.com/scomans/MyPet/files/6799252/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:** 

This server is running Paper version git-Paper-780 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**MyPet Build/Version:** MyPet-3.11-SNAPSHOT-B1641

**What is the expected result?** pet die have cooldown, like before

**What happens instead of that?** i don't know, this works before : (

**Error:**

show when pet die and respawn instantly
```
https://paste.gg/p/anonymous/1251f09abe804a149c1df7294b723dc0
```

**Comment by niqoar** [comment]
#1407
